name: packagename

channels:
    - http://ssb.stsci.edu/astroconda

dependencies:
    - setuptools
    - numpy
    - python>=3.0
    - pip:
      - sphinx-automodapi
      - stsci_rtd_theme
      - nbsphinx
